services:
  harvester:
    build:
      context: .		# <- repo root
      dockerfile: harvester/Dockerfile
    ports:
      - "8010:8000"
    env_file:
      - .env 
    environment:
      #- AWS_DEFAULT_REGION=eu-north-1
      #- AWS_REGION=eu-north-1
      - AWS_PROFILE=default
    volumes:
      - ~/.aws:/root/.aws
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  default:
    name: wae-news-analysis-network

